name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  progress_dialog: ^1.2.2
  flutter_facebook_login: 3.0.0
  http: 0.12.1
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  cached_network_image: ^2.1.0+1
  provider:
  local_auth: ^0.6.1
  font_awesome_flutter: ^8.4.0
  flutter_cupertino_localizations: ^1.0.1
  charts_flutter: ^0.8.1
  uuid:
  rect_getter: ^0.0.1
  flutter_launcher_icons: ^0.7.2+1
  flutter_local_notifications: ^0.8.0
  datetime_picker_formfield: ^1.0.0
  flare_flutter:
  yaml: ^2.2.0
  flutter_hooks: ^0.7.0
  get_it: ^3.1.0
  google_sign_in: ^4.0.1+3

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  test:
  mockito:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.5.1


flutter:

  uses-material-design: true
  assets:
    - assets/images/
